- kind: ethereum
  name: YieldVault
  network: mainnet
  source:
    address: "0x8d08948eca2587f5c10159e483b660e98cd5a514"
    abi: YieldVault
    startBlock: 11052984 # Block the vault was deployed
  mapping:
    kind: ethereum/events
    apiVersion: 0.0.7
    language: wasm/assemblyscript
    entities:
      - Deposit
      - Withdrawal
    abis:
      - name: YieldVault
        file: ./abis/YieldVault.json
    eventHandlers:
      - event: Deposited(indexed address,uint256,uint256)
        handler: handleDeposited
      - event: Withdrawn(indexed address,uint256,uint256)
        handler: handleWithdrawn
    file: ./src/yield-vault.ts
